
import React, { memo } from 'react';

interface PassageViewProps {
    id: string;
    currentPassage: number;
    splitWidth: number;
}

const PassageView: React.FC<PassageViewProps> = memo(({ id, currentPassage, splitWidth }) => {
    return (
        <div
            className="overflow-y-auto bg-gray-50/50 px-12 py-12 scroll-smooth selection:bg-amber-200 selection:text-amber-900"
            style={{ width: `${splitWidth}%` }}
        >
            <div className="max-w-3xl mx-auto space-y-8">
                {id === 'r1' && (
                    <>
                        {currentPassage === 0 && (
                            <div className="passage-content animate-in fade-in slide-in-from-bottom-4 duration-700">
                                <h2 className="text-xs font-black text-primary uppercase tracking-[0.3em] mb-4">Reading Passage 1</h2>
                                <h1 className="text-4xl font-black text-secondary leading-tight mb-8">The Clipper Races: an era of competition between cargo ships</h1>
                                <div className="prose prose-slate prose-lg max-w-none text-gray-600 leading-relaxed space-y-6">
                                    <p>During the seventeenth and eighteenth centuries, the British East India Company had the monopoly on trade with China and India. This meant that because no rival could legally import tea or other goods from these countries at this time, the company was rarely in a hurry to transport its merchandise. Instead, its priority was to minimise costs by carrying as much as possible on each ship. This meant that its ships - known as East Indiamen - were enormous, strong and very slow.</p>
                                    <p>By 1800, the average East Indiaman could carry 1,200 tons of merchandise. The trading pattern for China tea usually meant the East Indiamen set sail from Britain in January, sailed round the Cape of Good Hope at the southernmost tip of Africa, and arrived in China in September. There they would load up that year's tea harvest, set off again and, depending on the wind and weather, aim to arrive back by the following September. So even with favourable sailing conditions, the round trip lasted almost two years, and if anything went wrong it could take a lot longer.</p>
                                    <p>However, by 1834 the company had lost its trading monopolies, and tea had become a freely traded item. Having no more use for its great ships, the company sold them off, and many were bought by merchants or their captains, who continued to plough the seas between Britain and China. But now that tea could be traded freely, a few smart sailors began to realise that whoever brought each new harvest of tea to Britain first, stood to make the most money.</p>
                                    <p>This was partly because if you were home first, you could sell your shipment of tea before your competitors even arrived, and partly because consumers in Britain in the nineteenth century believed that the fresher and earlier-picked the tea, the better the resulting drink. Tea traders now needed faster, sleeker ships to bring their precious cargo back. Nevertheless, in Britain this idea only caught on slowly, and while the 1840s saw a few faster ships launched, for the time being many merchants remained satisfied with the slow but reliable East Indiamen.</p>
                                    <p>In fact it was the Americans who pioneered the first clipper ships. These vessels were fast and slender, with a narrow hull that was deeper at the back than at the front and masses of sails on tall masts. They earned their name from the way that they clipped off journey times. British merchants resolved to build their own clippers to rival the Americans and the first British tea clipper, Stornaway, was built in Aberdeen in 1850. More tea clippers were designed and built in Britain throughout the 1850s and 1860s; they had a narrower beam than their American equivalents, making them less powerful during storms, but faster in calmer weather.</p>
                                    <p>There was a great spirit of competition between the British and American ships plying the tea trade, but to begin with the Americans had the edge. Then in 1851 a British ship owner, Richard Green, built the aptly named clipper Challenger, with the stated intention of beating the American ships. Loaded with tea, Challenger left China for London in 1852 at the same time as the American clipper Challenge, a much larger, older ship, already greatly admired for its speed. Large sums were bet on which would complete the journey first. In the event, the British ship beat its rival to London by two days, amid much jubilation. From then on, such international races grew in popularity.</p>
                                    <p>After 1855, American participation in the British tea trade gradually stopped. But even without the Anglo-American rivalry, the competitive spirit continued. It was really ignited when new ports were opened up for trade in China. These included Fouchow, which was much closer to the tea-producing areas than Canton, the port used previously. As a result, tea could be loaded onboard earlier and fresher, and the clippers could set off in late May or early June - sometimes not even taking time to fill out the official paperwork - racing back to Britain whatever the difficulties.</p>
                                    <p>They sped down through the South China Sea and into the Indian Ocean, then raced to get round the southernmost tip of Africa at the Cape of Good Hope. Then it was north across the vast Atlantic, past the Azores, through the English Channel and into the estuary of the River Thames. Once there, they would be towed by tugs, up the river and into the docks.</p>
                                    <p>The cargo of the winning ship could earn a premium of up to sixpence per pound - and so the captain and crew were rewarded by the owners of the cargo. But the races were about more than just money: the crews, about 40 men on each clipper, were expert sailors, proud of their ships, and they delighted in competing against each other. Without their enthusiasm, the races would never have happened, since getting the ship home as fast as possible required the crew to be totally dedicated and to sacrifice much of their rest for the duration of the race.</p>
                                </div>
                            </div>
                        )}
                        {currentPassage === 1 && (
                            <div className="passage-content animate-in fade-in slide-in-from-bottom-4 duration-700">
                                <h2 className="text-xs font-black text-primary uppercase tracking-[0.3em] mb-4">Reading Passage 2</h2>
                                <h1 className="text-4xl font-black text-secondary leading-tight mb-8">Orientation of birds</h1>
                                <div className="prose prose-slate prose-lg max-w-none text-gray-600 leading-relaxed space-y-6">
                                    <p><strong>A</strong> For many of us, the way birds are able to orientate is both astounding and difficult to appreciate fully. For instance, the annual migration of the golden plover of the Pacific takes it from Alaska to Hawaii on a flight of well over 3000 kilometres, and if it were to deviate by only one degree, it would miss the island on which it nests.</p>
                                    <p><strong>B</strong> The first systematic studies on orientation in birds were made possible by the 'homing instinct' exhibited by so many species. Birds are caught at a time when they show an attachment to their territory, especially during the nesting season. They are taken to some spot, released, and the percentage of returns is recorded. The distance can be varied, and the direction, as well as the method of transporting them, and then the influence of climatic and other factors on their ability to find their way home can be studied. These experiments have shown a wide variation in ability to home, and three types of homing behaviour have been identified.</p>
                                    <p><strong>C</strong> In the first type, birds methodically explore the area in which they are released until they pick up some familiar feature, and then they quickly find their way back to the nest. Such birds possess a highly developed visual memory, as experiments with pigeons have shown. Domestic pigeons have been trained to peck at a certain point on an aerial photograph, with a system of rewards, and four years later the birds were still able to respond to this training when placed on the aerial photograph. Birds' eyes have a power of resolution two to three times greater than ours, enabling them to pick up very fine details. If a bird uses only this type of homing behaviour, however, it can only succeed if the point of release is not too far away. If the birds are transported 800 kilometres from their nest, it is only by good fortune that they find their way back as a result of long exploratory flights. Usually, the area known to a bird is its feeding territory. Released within this area, the birds soon make their return; release them outside it and far fewer return. However, if a bird is released for a second time in the same place, its visual memory comes into play, and the bird, no longer requiring tedious exploratory flights, will return much more quickly.</p>
                                    <p><strong>D</strong> The second type of homing behaviour is shown by birds that are capable of choosing their flight direction and holding to it for the rest of their journey. How do they decide what direction to take? They appear to choose their normal migration direction even if they are released in a different place from their usual starting point. If, for example, birds which normally fly to the north-east to reach latitude 45 degrees north are released at that latitude, they will immediately start flying north-east anyway. So if they're released further to the west, they'll maintain the correct direction, but fly west of their destination, and so fail to arrive.</p>
                                    <p><strong>E</strong> The third type of homing behaviour shows the highest degree of orientation. Released at one point, the birds immediately take stock of it, compare its position with that of the nest, decide on the direction and fly off. This happens even if the birds are in a country right off their migration routes, where they have never been before. In one example, a laysan albatross returned to its nesting area on Midway Island in the middle of the Pacific, having flown over 5000 kilometres from the west coast of the USA in just over ten days. This is a perfect example of the third type of homing, for the albatross clearly couldn't rely on any landmarks over the vast expanse of the Pacific Ocean.</p>
                                    <p><strong>F</strong> The percentage of successful birds varies greatly, being highest in those species with a strong migratory behaviour. Thus the lesser black-backed gull is more migratory than the herring gull and more often reaches 'home'. Great migrants such as the swift have the highest percentage of returns. In one case, seven out of nine alpine swifts were recaptured at their nests after being displaced some 1400 kilometres; one made the journey in three days.</p>
                                    <p><strong>G</strong> What part does heredity play in all this? Two research studies suggest that instinctive, i.e. genetically inherited, behaviour patterns play a part in navigation. The first was carried out by Ernst Schuz and it is highly significant. Schuz caught first year European storks and released them later, after the departure of the adult storks at a time when they normally make their south-west autumn migration to Africa. The recaptures showed that, in spite of the fact that there were no adults to guide them, the birds unanimously headed south-west. This was a most striking finding, for it showed that the birds had an innate and unlearned attraction for the African wintering area that they have occupied for thousands of years.</p>
                                    <p><strong>H</strong> The case of starlings is a little different. These birds have a great aptitude for homing, but this behaviour differs in the different age groups. Birds that were shifted to the south-east of their normal migration route split into two lot. The adults, in full possession of their gift for orientation, found their wintering area by modifying their direction by 90 degrees, whereas the juveniles sought their winter quarters to the south-east of their real position.</p>
                                </div>
                            </div>
                        )}
                        {currentPassage === 2 && (
                            <div className="passage-content animate-in fade-in slide-in-from-bottom-4 duration-700">
                                <h2 className="text-xs font-black text-primary uppercase tracking-[0.3em] mb-4">Reading Passage 3</h2>
                                <h1 className="text-4xl font-black text-secondary leading-tight mb-8">The role of accidents in business</h1>
                                <div className="prose prose-slate prose-lg max-w-none text-gray-600 leading-relaxed space-y-6">
                                    <p>In 1894 Dr John Kellogg and his brother, Will, were supervising a hospital and health spa in Michigan. The patients were on a restricted diet. One day, the brothers left cooked wheat untended for more than 24 hours. When they returned, they saw what they had done. It was no good to eat, but they decided to run the stale wheat through rollers, just to see how it would turn out. Normally, the process produced long sheets, but they were surprised to discover that this time the rollers created flat flakes. They baked them, and then tried the same thing with corn. From this accidental discovery came the cornflakes that generations have now been eating for breakfast.</p>
                                    <p>Accidents happen; there is nothing predictable and orderly about innovation. Nobel laureate Sir Alan Hodgkin, who discovered how nerve cells transmit electrical impulses between the skin and the brain, commented: 'I believe that the record of my published papers conveys an impression of directedness and planning which does not at all coincide with the actual sequence of events.'</p>
                                    <p>The same rule applies in business. The mistake that gave us cornflakes keeps repeating itself in the history of disruptive innovation, the kind that transforms markets. Louis Daguerre, for instance, discovered the technique that gave us photography in the 1830s, when drops of mercury from a shattered thermometer produced a photographic image. The microwave was discovered when Percy Spencer, a scientist with Raytheon, was testing a new vacuum tube and discovered that the sweet in his pocket had melted. The artificial sweetener, saccharin, was the unintentional result of a medical scientist's work on a chemical treatment for gastric ulcers. While working for the firm 3M, researcher Art Fry had no idea he was taking the first steps towards Post-It Notes when he used bits of adhesive office paper that could be easily lifted off the page to replace the scrap paper bookmarks that kept falling out of his hymn book.</p>
                                    <p>Breakthrough and disruptive innovation are rarely driven by orderly process. Usually they come out of a chaotic, haphazard mess, which is why big companies, full of managers schooled in business programmes designed to eliminate random variation and mistakes, struggle with them. In these sorts of environments, accidents are called failures and are discouraged.</p>
                                    <p>It is no surprise then that research from the late British economist Paul Geroski and London Business School's Constantinos Markides found that companies that were skilled at innovation were usually not that skilled when it came to commercialisation, and vice versa. Their book, <em>Fast Second</em>, divides businesses into 'colonists' and 'consolidators'. Small and nimble, colonists are adept at creating market niches but are terrible institution builders. Consolidators, with their strong cultures of discipline and cost control, know how to take clever ideas from other firms and turn them into mass-market items. Microsoft is a prime instance of this.</p>
                                    <p>With companies spending hundreds of billions of dollars on research and development, US academics Robert Austin and Lee Devin examined how managers can encourage productive slip-ups. In their article <em>Accident, Intention and Expectation in the Innovation Process</em>, they argue that business processes actually prevent helpful mis-steps from occurring. According to their catalogue of accidents, not all false steps and mishaps are equal. Accidents, they say, come from unlikely mental associations such as memories and vague connections, looking for something and finding it in an unexpected way, looking for one thing and finding something else, and not looking for anything but finding something valuable.</p>
                                    <p>Accident-prone innovation, they say, requires companies to get outside the 'cone of expectation'. It means throwing together groups from diverse backgrounds, and combining ideas in unpredictable ways. Other strategies also include having systems that watch out for accidents and examine them for value, generating them when they do not happen often enough, seizing all the useful ones, capturing their valuable features, and building on them to add value and give potential for useful accidents.</p>
                                    <p>All this, however, requires thinking that is often counter-intuitive to the way businesses operate. In other words, it is the kind of thinking that goes against the beliefs of most business managers. It runs counter to the notion frequently pushed by consultants that you can 'harness' creativity and direct it to line up with intention. 'The cost of accidents in business,' people tend to call such efforts failure.</p>
                                    <p>There are tentative signs that more companies are starting to realise that failure can lead to commercial gain, and that this is part of the risk-taking that underpins innovation. Australia's largest brewing company, for example, made a bad error when it launched a new beer called Empire Lager, pitched at younger consumers. Having spent a fortune creating a beer with a sweeter taste, designing a great-looking bottle and a television campaign, Foster's was left with a drink that no-one wanted to buy. The target market was more interested in brands built up by word of mouth.</p>
                                    <p>Instead of wiping the unsuccessful product launch, Foster's used this lesson learned to go on and develop other brands instead. One of them, Pure Blonde, is now ranked as Australia's fifth-largest beer brand. Unlike Empire Lager, there has been almost no promotion and its sales are generated more by word of mouth.</p>
                                    <p>Other companies are taking similar steps to study their own slip-ups. Intuit, the company behind financial tools such as Quicken, holds regular 'When Learning Hurts' sessions. But this sort of transformation is never easy. In a market that focuses on the short-term, convincing employees and shareholders to tolerate failure and not play it safe is a big thing to ask.</p>
                                </div>
                            </div>
                        )}
                    </>
                )}
                {id === 'r2' && (
                    <>
                        {currentPassage === 0 && (
                            <div className="passage-content animate-in fade-in slide-in-from-bottom-4 duration-700">
                                <h2 className="text-xs font-black text-primary uppercase tracking-[0.3em] mb-4">Reading Passage 1</h2>
                                <h1 className="text-4xl font-black text-secondary leading-tight mb-8">The Pyramid of Cestius</h1>
                                <div className="prose prose-slate prose-lg max-w-none text-gray-600 leading-relaxed space-y-6">
                                    <p>A 2000-year-old pyramid in the city of Rome has been restored by archaeologists</p>
                                    <p><strong>A</strong> Though Rome draws tourists from around the world to its many impressive sites, one notable monument there has never attracted nearly as much interest: The Pyramid of Cestius. But why would there be a pyramid in Italy? After the Roman conquest of Egypt in 30 B.C., Egyptian architectural style became the fashion in Rome. Though obelisks and other monuments inspired by Egypt's great pyramids sprung up around the city, only two actual pyramids are known to have been built. The only one left standing, the Pyramid of Cestius, was designed as the burial pyramid for a Roman politician named Caius Cestius, who ordered that the building work be completed within a period of 330 days.</p>
                                    <p><strong>B</strong> Construction took place at some point between 18 B.C. and 12 B.C. Cestius pyramid had a layer of white Carrara marble on the outside, and was constructed from brick held together by a basic kind of cement on the inside. One of the things that strikes you when you look at the pyramid is how steep it is, so that the shape of Cestius pyramid is quite unlike that of typical Egyptian ones. This is a difference that could have been the result of inaccurate information sent back to Rome by soldiers who saw the pyramids in person in Egypt. Alternatively, Roman builders could have drawn inspiration from the pyramids in Nubia, a region located in what is today northern Sudan and southern Egypt.</p>
                                    <p><strong>C</strong> At the time of its construction, since there was a strict Roman law prohibiting the placement of tombs within the city itself, the Pyramid of Cestius would have stood in countryside. Rome grew enormously during the next two centuries, and, by the 3rd century A.D., the pyramid would have been surrounded by buildings. We also know that in the 3rd century A.D., the Pyramid of Cestius was hidden behind a high wall on the orders of Emperor Aurelian; this probably helped it survive throughout the centuries to come, even as other ancient monuments disappeared.</p>
                                    <p><strong>D</strong> By the Middle Ages, the pyramid was covered in vegetation and thick dirt, and popular myth had developed that it might be a tomb for one of the twin brothers Romulus and Remus, who were regarded as the men who had established the city of Rome. Cestius actual tomb within the pyramid and the inscription identifying the pyramid as his, weren't rediscovered until the 1660s when the pyramid underwent restoration. During excavations, when trees and plants were cleared away, two marble bases were found in front of the pyramid, as well as fragments of bronze statues that had once stood on them on either side of the pyramid. The people employed to excavate the pyramid did not find the urn that would have contained Cestius’ remains, but they did come across a tunnel. It was quite possible, therefore, that robbers had at some earlier time removed the contents of the tomb. But while some of the features of Cestius' tomb no longer exist, at least the pyramid itself has survived.</p>
                                    <p><strong>E</strong> Today, the foundations of Cestius pyramid rest below street level near an intersection with heavy traffic, so that passing tourists and residents could easily fail to notice its full height of 119 feet. Across the intersection is the Piramide station, located on Line B of the Rome Metro. In 2011, the Japanese clothing company entrepreneur Yuzo Yagi, president of Yagi Tsusho Ltd, announced his intention to help the Italian government pay for an ambitious renovation of the Pyramid of Cestius. 'It's an act of gratitude,' he later told journalists. 'Our company has grown thanks to Italy.' Work began at the site shortly after Yagi signed an official agreement with the Special Superintendency for the Archaeological Heritage of Rome, and was completed ahead of schedule thanks to his 2-million-euro contribution.</p>
                                    <p><strong>F</strong> As archaeologist Leonardo Guarnieri explained to journalists, officials are now conducting tours of the newly renovated pyramid twice a month by reservation. Visitors who take advantage of the tour can make their way through a narrow corridor in order to enter the burial chamber itself. It is within these walls that they can admire the frescoes: watercolour paintings typical of the time. In the chamber, it is possible to make out four frescoes of the winged Roman goddess of war, Victoria a figure from Roman legend, as well as of a series of vases，the type that would have been used for special rituals and purification purposes. We know from the writings of earlier visitors that there used to be more here, but the majority have disappeared over time.</p>
                                    <p><strong>G</strong> Only one problem remains now that the restoration is complete. The white exterior of the Pyramid of Cestius will have to be cleaned every few months to remove the layer of urban pollution. A team of free-climbers will be employed to do the job, in order to avoid placing builder's scaffolding around the newly welcoming monument.</p>
                                </div>
                            </div>
                        )}
                        {currentPassage === 1 && (
                            <div className="passage-content animate-in fade-in slide-in-from-bottom-4 duration-700">
                                <h2 className="text-xs font-black text-primary uppercase tracking-[0.3em] mb-4">Reading Passage 2</h2>
                                <h1 className="text-4xl font-black text-secondary leading-tight mb-8">The conquest of malaria in Italy</h1>
                                <div className="prose prose-slate prose-lg max-w-none text-gray-600 leading-relaxed space-y-6">
                                    <p>A review of Frank M Snowden's masterly history of a country's fight to eradicate a deadly disease</p>
                                    <p><strong>A</strong> The word 'malaria' means 'bad air' in Italian, and this terrible disease marked the life of the people of that country for thousands of years. Yet by 1962, Italy was officially declared malaria-free, and it has remained so ever since. Frank Snowden's study of this successful endeavour is a remarkable piece of historical work. Original, crystal clear, analytical and passionate, Snowden takes us to areas historians have rarely visited before.</p>
                                    <p><strong>B</strong> Everybody now knows that malaria is carried by mosquitoes. But in the 19th century most experts subscribed to the theory of 'miasma' or 'poisoning of the air'. Others made a link between swamps, water and malaria, but did not make the further leap towards insects. The consequence of these theories was that little was done to combat the disease before the end of that century. The situation was so serious that from a total population of 25m Italians, 11m were 'permanently at risk'. In warm, damp, malarial zones, the life expectancy of land workers was a terrifying 22.5 years. The economic impact of the disease was immense. Epidemics were blamed on people who originated from the hotter parts of Italy, given the widespread belief that malaria was hereditary.</p>
                                    <p><strong>C</strong> One of the first breakthroughs in the war against malaria came in 1898 when the zoologist Giovanni Battista Grassi demonstrated that the micro-organisms causing the disease were carried in the digestive tract of the mosquito. By releasing mosquitoes into rooms to drink the blood of healthy human volunteers, Grassi was able to make the direct link between the insects and the disease. Definitive proof of this theory was obtained after an extraordinary series of experiments in Italy, where healthy people were introduced into malarial zones but kept free of mosquito bites - and remained well. The recently formed Italian state at last had the necessary information to begin tackling the disease.</p>
                                    <p><strong>D</strong> A complicated approach was adopted, which made use of quinine - a drug obtained from tree bark which had long been used to combat fever, but was now seen as a crucial part of the war on malaria. Italy introduced a quinine law and a quinine tax in 1904, and the drug was administered to large numbers of rural workers. Despite its often terrible side effects, the drug was successful in limiting the spread of the disease, and in breaking cycles of infection. In addition, Italy setup rural health centres and invested heavily in education programmes. Malaria, as Snowden shows, was not just a medical problem, but a social and regional issue, and could only be defeated through multi-layered strategies.</p>
                                    <p><strong>E</strong> It was originally decided to give quinine to all those in vulnerable regions - even healthy people. However, peasants were often suspicious of medicine being forced upon them, and doctors were frequently met with hostility and stubborn refusal to accept the treatment offered. But despite the refusals, the strategy as a whole was hugely successful. Deaths from malaria fell by some 80% in the first decade of the 20th century and some areas escaped altogether from the scourge of the disease.</p>
                                    <p><strong>F</strong> The 1915-18 war delayed the campaign, as funds were diverted to the battlefields. In the 1920s and 1930s the draining of the damp, unhealthy marshlands around Rome had a certain impact on the spread of malaria. However, as war swept through the drained lands in the 1940s, the disease returned with a vengeance. Yet the country's leading malariologist Alberto Missiroli refused to order the distribution of quinine, so allowing the epidemic to spread unchecked. According to Snowden, he did this in order to create the ideal conditions for a new strategy, supported by the US Rockefeller Foundation – a massive experiment involving the extermination of mosquitoes with the chemical DDT. It is estimated that more than a third of the inhabitants in the affected area contracted malaria and countless thousands died.</p>
                                    <p><strong>G</strong> With the end of the war in 1945, the US government and the Rockefeller Foundation were free to experiment. DDT was sprayed from the air, and 3m Italians had their bodies covered with the chemical. The effects were immense, and by 1962 malaria was more or less gone from the whole country. One of the final victims to die of the disease in Italy was the popular cyclist, Fausto Coppi. He had contracted malaria in Africa in 1960, and the failure of doctors in Italy to spot the disease was a sign of the times. A few decades earlier, they would have immediately noticed the telltale signs; it was later claimed that a small dose of quinine would have saved his life.</p>
                                    <p><strong>H</strong> As there are still more than 1m deaths every year from malaria worldwide, Snowden's book also has contemporary relevance. This is a disease that affects every level of the societies where it is rampant. The economic miracle of the 1950s and 1960s which made Italy into a modern industrial nation would not have been possible without the eradication of malaria. Moreover, this book convincingly argues that the disease was 'an integral part of the big picture of modern Italian history'. This magnificent study, beautifully written and impeccably documented, deserves an audience beyond specialists in history, or in Italy.</p>
                                </div>
                            </div>
                        )}
                        {currentPassage === 2 && (
                            <div className="passage-content animate-in fade-in slide-in-from-bottom-4 duration-700">
                                <h2 className="text-xs font-black text-primary uppercase tracking-[0.3em] mb-4">Reading Passage 3</h2>
                                <h1 className="text-4xl font-black text-secondary leading-tight mb-8">Images and Places</h1>
                                <div className="prose prose-slate prose-lg max-w-none text-gray-600 leading-relaxed space-y-6">
                                    <p>A new research method uses photography to try to explain why people form an attachment to certain places</p>
                                    <p>Human beings naturally become attached to places they visit or inhabit and these emotional attachments have become increasingly important in research on recreation sites and activities. Research into this phenomenon is called 'sense- of-place research'. This research has employed a variety of approaches to gauge people's feelings toward a place, including surveys and personal interviews, but so far has not used photo-based methods. However, Visitor Employed Photography (VEP), used to capture visitor perceptions of landscape and recreational quality, represents a potential innovation in sense-of-place research.</p>
                                    <p>A 'place' is a setting that we give meaning to based on the personal experiences, relationships and feelings we associate with it. A crucial distinction that needs to be made is between the more subjective concept of attachment and the symbolic 'meanings' or labels we use to describe the type of place a setting represents. Is, for example, a multiple-use forest area a wilderness? A playground? A workplace? Symbolic meanings are important in that they form the basis of our attachment to a place: we attribute meaning to our settings, and in turn become attached to the meanings (Stedman, 2003).</p>
                                    <p>All settings can have multiple meanings depending on how we encounter them. Some researchers suggest that, because meaning emerges through individual experience, for example 'my camping trip', place meanings are completely individualistic: a given setting such as a park will contain as many different meanings as there are people using the setting (Meinig, 1979). Others, however, (e.g. Grieder & Garkovich, 1994) assert that meanings are based on social categories and therefore are shared by others within these categories. For example, farmers share certain meanings for a plot of land that are distinct from those of real estate developers or hunters.</p>
                                    <p>Clearly, place attachment is built through familiarity with a place over a period of months or even years. Relph (1976) describes sense-of-place attachment as the steady accumulation of events within a setting; this creates 'home places'. According to this view, those who have participated fully in the life of the home or community, or have accumulated a series of everyday events in a setting, will have the strongest attachment to it. Extended residence in a place tends to make us feel toward it almost as a living thing, affecting our emotions in the same way as a family would (Ryden, 1993).</p>
                                    <p>However, Tuan (1977) notes that a sense of place may also develop quite rapidly in 'chosen places', where dramatic landscapes and intense experiences can lead to an immediate attachment. Indeed, many settings, especially those that attract visitors, may simultaneously exist as home places and chosen places.</p>
                                    <p>Clearly we are dealing with a complex phenomenon and photo-based research methods may help us to understand it better. In VEP, tourists are asked to take photographs. This technique has primarily been used to assess the perceptions of visitors to parks and recreation places. Haywood (1990) describes several benefits of VEP. Photography is an enjoyable, familiar activity to tourists which helps to sharpen observation and identify specific locations that are important. It can give clearer ideas on elements that are liked or disliked and also facilitates comparisons between places.</p>
                                    <p>However, several methodological issues need to be taken into account. First, who should take the photographs? VEP research typically involves visitors or tourists but, when applied to questions of attachment to a community, this approach has potential pitfalls. Chenoweth (1984) notes that research subjects may take photos that represent only a part of their entire recreational experience. This tendency probably relates to unfamiliarity with the setting. For example, when researchers assign the task of photographing a travel route with which respondents are not familiar, participants may save too many pictures and then use them all up at the end of their visit, even if there is no suitable material. Markwell (1997) noted an opposite tendency in his study of pictures taken on a nature tour: beginnings of excursions were over-represented, due perhaps to the initial novelty of the trip. Furthermore, Haywood (1990) suggests that compressing the photo-taking period into a single day (as he did in his work) may result in an over-representation of tourist icons rather than ordinary places.</p>
                                    <p>In contrast, Yamashita (2002), when focusing on local residents' perceptions of the qualities of the water around them, noted that residents may have more difficulty expressing visual appeal than visitors, precisely because they are insiders and less conscious of aesthetic qualities. When addressing complex attachment to landscape, we would expect, however, that familiarity ought to increase the validity of the items selected to represent sources of attachment. We also expect that photographs taken by local residents will represent a wider range of phenomena than pictures taken by transient visitors.</p>
                                    <p>But how should the photographs be interpreted? Goin (2001) notes that with every photo taken 'a fiction is created ... but presents to the uninformed an overwhelming conviction of fact' (p. 363). By implication, what photos appear to be and what they really represent may be very different things, and some follow-up helps to uncover the intended meanings of the participant. Yamashita (2002) notes the utility of asking respondents to provide descriptions of each photo in a notebook or diary. These elaborations are helpful, but in cases of complex phenomena, an interview may help participants clarify their intentions (Markwell, 1997).</p>
                                </div>
                            </div>
                        )}
                    </>
                )}
            </div>
        </div>
    );
});

export default PassageView;
